sudo: required # super user permissions
services:
  - docker  # install docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .  # set up to occure before test run or deployment

script:
  - docker run -e CI=true docker-react npm run test # commands to run test suit


deploy:
  provider: elasticbeanstalk  # service e.g aws digital ocean
  region: "us-east-1"  # area  elastic-beanstalk was created
  app: "docker-react" # name of elastic-beanstalk app
  env: "Dockerreact-env" # env in elastic-beanstalk
  bucket_name: "elasticbeanstalk-us-east-1-500350084356" # the hardrive used to store files
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"  # https://stackoverflow.com/questions/58774215/travis-ci-build-failed-awss3errorssignaturedoesnotmatch
    
