sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "test"
  env: "Test-env"
  bucket_name: "elasticbeanstalk-ap-south-1-500350084356"
  bucket_path: "test"
  on:
    branch: master
    
